# Generated by Django 2.2.24 on 2022-01-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FunManagement', '0007_funhistory_uid'),
        ('login', '0008_auto_20211129_1528'),
        ('PageManagement', '0007_pagehistory_uid'),
        ('ProjectManagement', '0018_prohistory_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementBaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementName', models.CharField(max_length=100, verbose_name='元素名称')),
                ('cuid', models.IntegerField(verbose_name='创建者用户')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('onlyCode', models.CharField(max_length=100, verbose_name='历史记录唯一码')),
                ('fun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FunManagement.FunManagement')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PageManagement.PageManagement')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.ProManagement')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
        migrations.CreateModel(
            name='ElementLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='数据排序')),
                ('targetingType', models.CharField(max_length=20, verbose_name='定位类型')),
                ('targetingPath', models.CharField(max_length=500, verbose_name='定位地址')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
                ('state', models.IntegerField(verbose_name='是否启用(0:禁用,1:启用)')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('onlyCode', models.CharField(max_length=100, verbose_name='历史记录唯一码')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ui_ElementMaintenance.ElementBaseData')),
            ],
        ),
    ]
