# Generated by Django 2.2.24 on 2022-01-26 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ui_CaseMaintenance', '0003_auto_20220126_1203'),
        ('login', '0008_auto_20211129_1528'),
        ('Ui_ElementMaintenance', '0005_elementbasedata_elementstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.IntegerField(verbose_name='是否已读(1:已看,0:未看)')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cuid', models.IntegerField(verbose_name='创建者用户')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ui_CaseMaintenance.UiCaseBaseData')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ui_ElementMaintenance.ElementBaseData')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
    ]
