# Generated by Django 2.2.24 on 2021-11-29 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promanagement',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable'),
        ),
    ]
