# Generated by Django 2.2.24 on 2021-11-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0002_auto_20211129_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='promanagement',
            name='cuid',
            field=models.IntegerField(default=3, verbose_name='创建者用户'),
            preserve_default=False,
        ),
    ]
