# Generated by Django 2.2.24 on 2021-11-30 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20211129_1528'),
        ('ProjectManagement', '0003_promanagement_cuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promanagement',
            name='createTime',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.CreateModel(
            name='ProBindMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.ProManagement')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
    ]
