# Generated by Django 2.2.24 on 2021-12-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0006_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='operationType',
            field=models.CharField(max_length=10, verbose_name='操作类型(Delete,Add,Edit)'),
        ),
    ]
