# Generated by Django 2.2.24 on 2021-12-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0007_auto_20211206_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='restoreData',
            field=models.TextField(null=True, verbose_name='恢复数据'),
        ),
    ]
