# Generated by Django 2.2.24 on 2021-12-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0008_history_restoredata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
