# Generated by Django 2.2.24 on 2021-12-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0010_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='pid',
        ),
        migrations.AddField(
            model_name='history',
            name='proName',
            field=models.CharField(default=1, max_length=20, verbose_name='项目名称'),
            preserve_default=False,
        ),
    ]
