# Generated by Django 2.2.24 on 2021-12-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0011_auto_20211210_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='pid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.ProManagement'),
            preserve_default=False,
        ),
    ]
