# Generated by Django 2.2.24 on 2021-12-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0012_history_pid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='ProHistory',
        ),
    ]
