# Generated by Django 2.2.24 on 2022-01-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0013_auto_20211213_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prohistory',
            name='restoreData',
            field=models.TextField(null=True, verbose_name='恢复数据,此数据主要保存基础数据'),
        ),
    ]
