# Generated by Django 2.2.24 on 2022-01-06 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Api_TestReport', '0013_auto_20211228_1510'),
        ('Api_CaseMaintenance', '0003_auto_20220104_1432'),
        ('login', '0008_auto_20211129_1528'),
        ('PageEnvironment', '0002_auto_20211208_1146'),
        ('ProjectManagement', '0013_auto_20211213_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTimingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=20, verbose_name='任务名称')),
                ('timingConfig', models.CharField(max_length=50, verbose_name='定时配置')),
                ('priority', models.CharField(max_length=10, verbose_name='优先级(P0-P3)')),
                ('pushTo', models.CharField(max_length=100, null=True, verbose_name='接收邮件')),
                ('taskStatus', models.IntegerField(verbose_name='任务状态(0:禁用,1:启用)')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('cuid', models.IntegerField(verbose_name='创建人')),
                ('is_del', models.IntegerField(verbose_name='是否删除(0:删除,1:不删除)')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PageEnvironment.PageEnvironment')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.ProManagement')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
        migrations.CreateModel(
            name='ApiTimingTaskTestSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='排序')),
                ('state', models.IntegerField(verbose_name='是否启用(0:禁用,1:启用)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_del', models.IntegerField(verbose_name='是否删除(0:删除,1:不删除)')),
                ('TimingTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_TimingTask.ApiTimingTask')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_CaseMaintenance.CaseBaseData')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
        migrations.CreateModel(
            name='ApiTimingTaskRunLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runType', models.CharField(max_length=10, verbose_name='运行类型(手动(Manual)/自动(Auto))')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('TimingTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_TimingTask.ApiTimingTask')),
                ('testReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_TestReport.ApiTestReport')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
    ]
