# Generated by Django 2.2.24 on 2022-01-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitimingtasktestset',
            old_name='TimingTask',
            new_name='timingTask',
        ),
    ]
