# Generated by Django 2.2.24 on 2022-01-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0002_auto_20220106_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitimingtask',
            name='remarks',
            field=models.TextField(null=True, verbose_name='备注信息'),
        ),
    ]
