# Generated by Django 2.2.24 on 2022-01-07 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0004_apitimingtasktestset_historycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTimingTaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historyCode', models.CharField(max_length=100, verbose_name='历史记录唯一码')),
                ('operationType', models.CharField(max_length=10, verbose_name='操作类型(Add,Edit,Delete)')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('timingTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_TimingTask.ApiTimingTask')),
            ],
        ),
    ]
