# Generated by Django 2.2.24 on 2022-01-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0006_apitimingtask_historycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitimingtask',
            name='historyCode',
        ),
        migrations.AddField(
            model_name='apitimingtaskhistory',
            name='restoreData',
            field=models.TextField(null=True, verbose_name='恢复数据,用来存放基础数据'),
        ),
    ]
