# Generated by Django 2.2.24 on 2022-01-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0007_auto_20220107_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitimingtask',
            name='historyCode',
            field=models.CharField(max_length=100, null=True, verbose_name='历史记录唯一码,保存在最后更新此码'),
        ),
    ]
