# Generated by Django 2.2.24 on 2022-01-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20211129_1528'),
        ('Api_TimingTask', '0009_auto_20220107_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitimingtaskhistory',
            name='uid',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='login.UserTable'),
            preserve_default=False,
        ),
    ]
