# Generated by Django 2.2.24 on 2022-01-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0010_apitimingtaskhistory_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitimingtask',
            name='historyCode',
        ),
    ]
