# Generated by Django 2.2.24 on 2022-01-07 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0012_apitimingtask_historycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitimingtaskhistory',
            name='historyCode',
        ),
        migrations.AddField(
            model_name='apitimingtasktestset',
            name='history',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api_TimingTask.ApiTimingTaskHistory'),
            preserve_default=False,
        ),
    ]
