# Generated by Django 2.2.24 on 2022-01-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0015_auto_20220107_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitimingtasktestset',
            name='historyCode',
        ),
    ]
