# Generated by Django 2.2.24 on 2022-01-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0016_remove_apitimingtasktestset_historycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitimingtasktestset',
            name='history',
        ),
        migrations.AddField(
            model_name='apitimingtasktestset',
            name='historyCode',
            field=models.CharField(default=1, max_length=100, verbose_name='历史记录唯一码'),
            preserve_default=False,
        ),
    ]
