# Generated by Django 2.2.24 on 2022-01-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('Api_TimingTask', '0017_auto_20220107_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitimingtask',
            name='periodicTask',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djcelery.PeriodicTask'),
            preserve_default=False,
        ),
    ]
