# Generated by Django 2.2.24 on 2022-01-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0018_apitimingtask_periodictask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitimingtask',
            name='periodicTask',
        ),
    ]
