# Generated by Django 2.2.24 on 2022-01-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0019_remove_apitimingtask_periodictask'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitimingtask',
            name='periodicTask_id',
            field=models.IntegerField(null=True, verbose_name='内置任务ID'),
        ),
    ]
