# Generated by Django 2.2.24 on 2022-01-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0020_apitimingtask_periodictask_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitimingtaskhistory',
            name='historyCode',
            field=models.CharField(max_length=100, null=True, verbose_name='历史记录唯一码'),
        ),
    ]
