# Generated by Django 2.2.24 on 2022-01-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0021_auto_20220111_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitimingtaskrunlog',
            old_name='TimingTask',
            new_name='timingTask',
        ),
    ]
