# Generated by Django 2.2.24 on 2022-01-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0023_auto_20220113_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitimingtaskrunlog',
            name='taskName',
            field=models.CharField(default=1, max_length=20, verbose_name='任务名称'),
            preserve_default=False,
        ),
    ]
