# Generated by Django 3.2.9 on 2021-11-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysType', models.CharField(max_length=10, null=True, verbose_name='所属页面(Home/API/UI/PTS)')),
                ('level', models.IntegerField(verbose_name='菜单级别 1,2')),
                ('index', models.CharField(max_length=50, null=True, verbose_name='菜单index')),
                ('menuName', models.CharField(max_length=50, null=True, verbose_name='菜单名称')),
                ('routerPath', models.CharField(max_length=100, null=True, verbose_name='路由地址')),
                ('belogId', models.IntegerField(null=True, verbose_name='上级id')),
                ('is_del', models.IntegerField(verbose_name='是否删除(0:删除,1:不删除)')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
