# Generated by Django 3.2.9 on 2021-11-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerPar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
