# Generated by Django 3.2.9 on 2021-11-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerPar', '0002_router_updatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='sortNum',
            field=models.IntegerField(default=1, verbose_name='排序'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='router',
            name='is_del',
            field=models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)'),
        ),
    ]
