# Generated by Django 3.2.9 on 2021-11-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routerPar', '0003_auto_20211123_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='index',
        ),
    ]
