# Generated by Django 3.2.9 on 2021-11-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerPar', '0004_remove_router_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='index',
            field=models.CharField(max_length=50, null=True, verbose_name='菜单index'),
        ),
    ]
