# Generated by Django 3.2.9 on 2021-11-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerPar', '0005_router_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='sortNum',
            field=models.IntegerField(null=True, verbose_name='排序'),
        ),
    ]
