# Generated by Django 3.2.9 on 2021-11-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerPar', '0006_alter_router_sortnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='icon',
            field=models.CharField(max_length=50, null=True, verbose_name='菜单图标'),
        ),
    ]
