# Generated by Django 2.2.24 on 2021-11-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerPar', '0007_router_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='router',
            name='sysType',
            field=models.CharField(max_length=10, null=True, verbose_name='所属页面(HOME/API/UI/PTS)'),
        ),
    ]
