# Generated by Django 2.2.24 on 2021-12-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TestReport', '0003_auto_20211214_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apireport',
            name='requestFile',
        ),
        migrations.AlterField(
            model_name='apitestreport',
            name='reportStatus',
            field=models.CharField(max_length=10, verbose_name='测试报告状态(Pass,Fail,Error)'),
        ),
    ]
