# Generated by Django 2.2.24 on 2021-12-14 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20211129_1528'),
        ('Api_TestReport', '0005_apitestreport_runningtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.IntegerField(verbose_name='任务ID,apiId,CaseId,TaskId,BatchId')),
                ('queueStatus', models.IntegerField(verbose_name='队列执行状态(0:未开始,1:执行中,2:已结束)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_TestReport.ApiTestReport')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
    ]
