# Generated by Django 2.2.24 on 2021-12-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0013_auto_20211213_1048'),
        ('Api_TestReport', '0007_auto_20211214_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiqueue',
            name='pid',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.ProManagement'),
            preserve_default=False,
        ),
    ]
