# Generated by Django 2.2.24 on 2021-12-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TestReport', '0008_apiqueue_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiqueue',
            name='taskType',
            field=models.CharField(default=1, max_length=50, verbose_name='任务类型(API:单接口,Case,Task:定时任务,batch:批量任务)'),
            preserve_default=False,
        ),
    ]
