# Generated by Django 2.2.24 on 2021-12-15 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageManagement', '0005_pagehistory'),
        ('Api_TestReport', '0009_apiqueue_tasktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiqueue',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PageManagement.PageManagement'),
            preserve_default=False,
        ),
    ]
