# Generated by Django 2.2.24 on 2021-12-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TestReport', '0011_apiqueue_fun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apireport',
            name='responseMethods',
        ),
        migrations.AddField(
            model_name='apireport',
            name='preOperationInfo',
            field=models.TextField(null=True, verbose_name='前置操作返回信息'),
        ),
        migrations.AddField(
            model_name='apireport',
            name='rearOperationInfo',
            field=models.TextField(null=True, verbose_name='后置操作返回值'),
        ),
    ]
