# Generated by Django 2.2.24 on 2021-12-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TestReport', '0012_auto_20211216_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apireport',
            name='statusCode',
            field=models.IntegerField(null=True, verbose_name='返回代码'),
        ),
    ]
