# Generated by Django 2.2.24 on 2022-01-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TimingTask', '0021_auto_20220111_1124'),
        ('Api_TestReport', '0014_auto_20220107_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apireportitem',
            old_name='ctbId',
            new_name='case_id',
        ),
        migrations.AddField(
            model_name='apireportitem',
            name='batchItem_id',
            field=models.IntegerField(null=True, verbose_name='Batch类型时才有此ID'),
        ),
        migrations.CreateModel(
            name='ApiReportTaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=50, null=True, verbose_name='定时任务名称')),
                ('runningTime', models.FloatField(null=True, verbose_name='运行总时间')),
                ('successTotal', models.IntegerField(verbose_name='成功数')),
                ('failTotal', models.IntegerField(verbose_name='失败数')),
                ('errorTotal', models.IntegerField(verbose_name='错误数')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_TimingTask.ApiTimingTask')),
                ('testReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_TestReport.ApiTestReport')),
            ],
        ),
    ]
