# Generated by Django 2.2.24 on 2022-01-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_TestReport', '0015_auto_20220111_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestreport',
            name='createTime',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
