# Generated by Django 2.2.24 on 2022-01-13 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0008_auto_20211129_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysType', models.CharField(max_length=10, verbose_name='所属系统')),
                ('keyName', models.CharField(max_length=100, verbose_name='参数名称')),
                ('value', models.CharField(max_length=100, null=True, verbose_name='参数值')),
                ('valueType', models.CharField(max_length=10, verbose_name='参数值')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
    ]
