# Generated by Django 2.2.24 on 2022-01-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemParams', '0002_auto_20220113_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemparams',
            name='label',
            field=models.CharField(default=1, max_length=20, verbose_name='标签'),
            preserve_default=False,
        ),
    ]
