# Generated by Django 3.2.9 on 2021-11-24 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0006_auto_20211123_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=10, null=True, verbose_name='角色名称')),
                ('dataType', models.IntegerField(verbose_name='数据类别(0:系统级别,不可删除/1:普通级别,可删除)')),
                ('is_del', models.IntegerField(verbose_name='是否删除(0:删除,1:不删除)')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usertable')),
            ],
        ),
    ]
