# Generated by Django 3.2.9 on 2021-11-24 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routerPar', '0006_alter_router_sortnum'),
        ('login', '0006_auto_20211123_1457'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicrole',
            name='is_del',
            field=models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)'),
        ),
        migrations.CreateModel(
            name='RoleBindMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysType', models.CharField(max_length=10, verbose_name='归属页面')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.basicrole')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routerPar.router')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usertable')),
            ],
        ),
    ]
