# Generated by Django 2.2.24 on 2021-11-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_auto_20211124_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicrole',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rolebindmenu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rolebindmenu',
            name='sysType',
            field=models.CharField(max_length=10, verbose_name='所属系统'),
        ),
    ]
