# Generated by Django 2.2.24 on 2021-11-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_auto_20211129_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicrole',
            name='is_admin',
            field=models.IntegerField(default=0, verbose_name='是否是管理组(1:是,0:不是)'),
            preserve_default=False,
        ),
    ]
