# Generated by Django 2.2.24 on 2021-12-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageManagement', '0003_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
