# Generated by Django 3.2.9 on 2021-11-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ErrorMsg',
            new_name='ErrorInfo',
        ),
    ]
