# Generated by Django 3.2.9 on 2021-11-22 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_delete_errormsg'),
        ('info', '0002_rename_errormsg_errorinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorinfo',
            name='sys',
            field=models.CharField(max_length=10, verbose_name='系统类型(Login/Int/Fun/Per)'),
        ),
        migrations.CreateModel(
            name='OperateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysType', models.CharField(max_length=10, verbose_name='系统类型(Int/Fun/Per)')),
                ('toPage', models.CharField(max_length=100, verbose_name='所属页面')),
                ('toFun', models.CharField(max_length=100, verbose_name='所属功能')),
                ('CUFront', models.TextField(null=True, verbose_name='修改前信息')),
                ('CURear', models.TextField(null=True, verbose_name='修改后信息')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usertable')),
            ],
        ),
    ]
