# Generated by Django 3.2.9 on 2021-11-22 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20211122_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorinfo',
            old_name='sys',
            new_name='sysType',
        ),
    ]
