# Generated by Django 3.2.9 on 2021-11-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_rename_sys_errorinfo_systype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorinfo',
            name='sysType',
            field=models.CharField(max_length=10, verbose_name='系统类型(API/UI/PTS)'),
        ),
        migrations.AlterField(
            model_name='operateinfo',
            name='sysType',
            field=models.CharField(max_length=10, verbose_name='系统类型(Login/API/UI/PTS)'),
        ),
    ]
