# Generated by Django 3.2.9 on 2021-11-25 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_errorinfo_systype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operateinfo',
            old_name='uid',
            new_name='cuid',
        ),
    ]
