# Generated by Django 3.2.9 on 2021-11-25 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_rename_uid_operateinfo_cuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operateinfo',
            old_name='cuid',
            new_name='uid',
        ),
    ]
