# Generated by Django 3.2.9 on 2021-11-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_rename_cuid_operateinfo_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorInfo',
        ),
        migrations.AlterField(
            model_name='operateinfo',
            name='sysType',
            field=models.CharField(max_length=10, verbose_name='系统类型(ALL/Home/API/UI/PTS)'),
        ),
    ]
