# Generated by Django 3.2.9 on 2021-11-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20211125_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateinfo',
            name='info',
            field=models.TextField(null=True, verbose_name='报错信息'),
        ),
        migrations.AddField(
            model_name='operateinfo',
            name='is_read',
            field=models.IntegerField(default=1, verbose_name='是否删除(0:未读,1:已读)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operateinfo',
            name='level',
            field=models.IntegerField(null=True, verbose_name='提醒等级(错误(1),警告(2),新增和修改(3))'),
        ),
        migrations.AddField(
            model_name='operateinfo',
            name='remindType',
            field=models.CharField(max_length=10, null=True, verbose_name='提醒类别 Error,Warning,Add,Edit'),
        ),
    ]
