# Generated by Django 3.2.9 on 2021-11-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20211125_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateinfo',
            name='toFun',
            field=models.CharField(max_length=100, null=True, verbose_name='所属功能'),
        ),
        migrations.AlterField(
            model_name='operateinfo',
            name='toPage',
            field=models.CharField(max_length=100, null=True, verbose_name='所属页面'),
        ),
    ]
