# Generated by Django 3.2.9 on 2021-11-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_operateinfo_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateinfo',
            name='remindType',
            field=models.CharField(default=1, max_length=10, verbose_name='提醒类别 Error,Warning,Add,Edit,Other'),
            preserve_default=False,
        ),
    ]
