# Generated by Django 3.2.9 on 2021-11-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_auto_20211125_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateinfo',
            name='beingPushedUid',
            field=models.IntegerField(null=True, verbose_name='被推送者'),
        ),
        migrations.AlterField(
            model_name='operateinfo',
            name='sysType',
            field=models.CharField(max_length=10, verbose_name='系统类型(ALL(所有系统通用)/Login/Home/API/UI/PTS)'),
        ),
    ]
