# Generated by Django 3.2.9 on 2021-11-25 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_userbindrole'),
        ('info', '0015_auto_20211125_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operateinfo',
            name='beingPushedUid',
        ),
        migrations.AlterField(
            model_name='operateinfo',
            name='remindType',
            field=models.CharField(max_length=10, verbose_name='提醒类别 Error,Warning,Change(Add,Edit),Other'),
        ),
        migrations.CreateModel(
            name='PushInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.IntegerField(verbose_name='已接收(0:未接收,1:已接收)')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('oinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.operateinfo')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usertable')),
            ],
        ),
    ]
