# Generated by Django 3.2.9 on 2021-11-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20211125_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushinfo',
            name='received',
        ),
    ]
