# Generated by Django 2.2.24 on 2021-11-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_remove_pushinfo_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operateinfo',
            name='sysType',
            field=models.CharField(max_length=10, verbose_name='系统类型(ALL(所有系统通用)/LOGIN/HOME/API/UI/PTS)'),
        ),
        migrations.AlterField(
            model_name='pushinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
