# Generated by Django 2.2.24 on 2021-12-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_auto_20211202_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushinfo',
            name='is_read',
            field=models.IntegerField(default=1, verbose_name='是否删除(0:未读,1:已读)'),
            preserve_default=False,
        ),
    ]
