# Generated by Django 2.2.24 on 2021-12-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20211202_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateinfo',
            name='triggerType',
            field=models.CharField(max_length=10, verbose_name='触发类型:系统(System)/手动(Manual)'),
        ),
    ]
