# Generated by Django 2.2.24 on 2021-12-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_operateinfo_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateinfo',
            name='remindType',
            field=models.CharField(max_length=10, verbose_name='提醒类别 Error,Warning,Add,Edit,Delete,Update,Other'),
        ),
    ]
