# Generated by Django 2.2.24 on 2022-01-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0008_auto_20211129_1528'),
        ('Api_TimingTask', '0020_apitimingtask_periodictask_id'),
        ('ProjectManagement', '0013_auto_20211213_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBatchTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchName', models.CharField(max_length=20, verbose_name='任务名称')),
                ('priority', models.CharField(max_length=10, verbose_name='优先级(P0-P3)')),
                ('pushTo', models.CharField(max_length=100, null=True, verbose_name='接收邮件')),
                ('remarks', models.TextField(null=True, verbose_name='备注信息')),
                ('hookId', models.CharField(max_length=100, verbose_name='钩子ID，是一个随机码的唯一值')),
                ('hookState', models.IntegerField(verbose_name='是否开启(0:未开启,1:开启)')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('cuid', models.IntegerField(verbose_name='创建人')),
                ('is_del', models.IntegerField(verbose_name='是否删除(0:删除,1:不删除)')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.ProManagement')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
        migrations.CreateModel(
            name='ApiBatchTaskTestSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='排序')),
                ('state', models.IntegerField(verbose_name='是否启用(0:禁用,1:启用)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_del', models.IntegerField(verbose_name='是否删除(0:删除,1:不删除)')),
                ('batchTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_BatchTask.ApiBatchTask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_TimingTask.ApiTimingTask')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
    ]
