# Generated by Django 2.2.24 on 2022-01-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_BatchTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apibatchtask',
            name='historyCode',
            field=models.CharField(default=1, max_length=100, verbose_name='历史记录唯一码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apibatchtasktestset',
            name='historyCode',
            field=models.CharField(default=1, max_length=100, verbose_name='历史记录唯一码'),
            preserve_default=False,
        ),
    ]
