# Generated by Django 2.2.24 on 2022-01-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20211129_1528'),
        ('Api_BatchTask', '0002_auto_20220111_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBatchTaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historyCode', models.CharField(max_length=100, verbose_name='历史记录唯一码')),
                ('operationType', models.CharField(max_length=10, verbose_name='操作类型(Add,Edit,Delete)')),
                ('restoreData', models.TextField(null=True, verbose_name='恢复数据,用来存放基础数据')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('batchTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_BatchTask.ApiBatchTask')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
    ]
