# Generated by Django 2.2.24 on 2022-01-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_BatchTask', '0005_apibatchtaskrunlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apibatchtaskrunlog',
            name='versions',
            field=models.CharField(max_length=20, null=True, verbose_name='版本号'),
        ),
    ]
