# Generated by Django 2.2.24 on 2022-01-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_BatchTask', '0007_auto_20220112_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apibatchtask',
            name='historyCode',
        ),
        migrations.RemoveField(
            model_name='apibatchtaskhistory',
            name='historyCode',
        ),
        migrations.RemoveField(
            model_name='apibatchtasktestset',
            name='historyCode',
        ),
        migrations.AddField(
            model_name='apibatchtask',
            name='onlyCode',
            field=models.CharField(default=1, max_length=100, verbose_name='历史记录唯一码,新增的时候会创建1个'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apibatchtaskhistory',
            name='batchName',
            field=models.CharField(default=1, max_length=20, verbose_name='任务名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apibatchtaskhistory',
            name='onlyCode',
            field=models.CharField(default=1, max_length=100, verbose_name='历史记录唯一码,新增的时候会创建1个'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apibatchtasktestset',
            name='onlyCode',
            field=models.CharField(default=1, max_length=100, verbose_name='历史记录唯一码,新增的时候会创建1个'),
            preserve_default=False,
        ),
    ]
