# Generated by Django 2.2.24 on 2022-01-26 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ui_CaseMaintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiTestSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='排序')),
                ('state', models.IntegerField(verbose_name='是否启用(1:启用,0:禁用)')),
                ('eventName', models.CharField(max_length=50, null=True, verbose_name='事件名称')),
                ('elementId', models.IntegerField(null=True, verbose_name='元素ID')),
                ('elementType', models.CharField(max_length=100, null=True, verbose_name='最终元素操作类型')),
                ('inputData', models.CharField(max_length=500, null=True, verbose_name='输入/选择')),
                ('assertType', models.CharField(max_length=50, null=True, verbose_name='断言类型')),
                ('assertValueType', models.CharField(max_length=50, null=True, verbose_name='断言值类型')),
                ('assertValue', models.TextField(null=True, verbose_name='断言值')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('onlyCode', models.CharField(max_length=100, verbose_name='历史记录唯一码,新增的时候会创建1个')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ui_CaseMaintenance.UiCaseBaseData')),
            ],
        ),
    ]
