# Generated by Django 2.2.24 on 2022-01-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ui_CaseMaintenance', '0003_auto_20220126_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiOperationSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='排序')),
                ('state', models.IntegerField(verbose_name='是否启用(1:启用,0:禁用)')),
                ('location', models.CharField(max_length=20, verbose_name='位置 前/后(Pre,Rear)')),
                ('operationType', models.CharField(max_length=20, verbose_name='操作类型(Methods,DataBase,TestCase)')),
                ('methodsName', models.CharField(max_length=100, null=True, verbose_name='函数方法')),
                ('dataBaseId', models.CharField(max_length=50, null=True, verbose_name='要执行的数据库连接ID')),
                ('caseId', models.CharField(max_length=50, null=True, verbose_name='要执行的用例ID')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('onlyCode', models.CharField(max_length=100, verbose_name='历史记录唯一码,新增的时候会创建1个')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ui_CaseMaintenance.UiCaseBaseData')),
            ],
        ),
    ]
