# Generated by Django 2.2.24 on 2022-01-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ui_CaseMaintenance', '0004_uioperationset'),
    ]

    operations = [
        migrations.AddField(
            model_name='uioperationset',
            name='sql',
            field=models.TextField(null=True, verbose_name='SQL'),
        ),
    ]
