# Generated by Django 2.2.24 on 2021-12-01 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0008_auto_20211129_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkorderManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysType', models.CharField(max_length=10, verbose_name='所属系统')),
                ('workType', models.CharField(max_length=20, verbose_name='工单类型(Add,Edit,Delete,Other)')),
                ('workState', models.IntegerField(verbose_name='工单状态(0:待受理,1:受理中,2:已解决)')),
                ('workName', models.CharField(max_length=20, verbose_name='工单名称')),
                ('message', models.TextField(null=True, verbose_name='工单信息')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('cuid', models.IntegerField(verbose_name='创建者用户')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
        migrations.CreateModel(
            name='WorkBindPushToUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkorderManagement.WorkorderManagement')),
            ],
        ),
    ]
