# Generated by Django 2.2.24 on 2021-12-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0005_probindmembers_role'),
        ('FunManagement', '0002_funmanagement_systype'),
        ('PageManagement', '0002_pagemanagement_systype'),
        ('WorkorderManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermanagement',
            name='fun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FunManagement.FunManagement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workordermanagement',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PageManagement.PageManagement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workordermanagement',
            name='pid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.ProManagement'),
            preserve_default=False,
        ),
    ]
