# Generated by Django 2.2.24 on 2021-12-02 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20211129_1528'),
        ('WorkorderManagement', '0003_workordermanagement_worksource'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLifeCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.TextField(null=True, verbose_name='操作信息字典类型')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkorderManagement.WorkorderManagement')),
            ],
        ),
    ]
