# Generated by Django 2.2.24 on 2021-12-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkorderManagement', '0004_worklifecycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worklifecycle',
            old_name='operation',
            new_name='operationInfo',
        ),
        migrations.AddField(
            model_name='worklifecycle',
            name='operationType',
            field=models.CharField(default=1, max_length=10, verbose_name='操作类型(Add,Edit)'),
            preserve_default=False,
        ),
    ]
