# Generated by Django 2.2.24 on 2021-12-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkorderManagement', '0006_auto_20211202_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklifecycle',
            name='workState',
            field=models.IntegerField(default=1, verbose_name='工单状态(0:待受理,1:受理中,2:已解决,3:已关闭)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workordermanagement',
            name='workState',
            field=models.IntegerField(verbose_name='工单状态(0:待受理,1:受理中,2:已解决,3:已关闭)'),
        ),
    ]
