# Generated by Django 2.2.24 on 2022-01-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkorderManagement', '0009_historyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordermanagement',
            name='message',
        ),
    ]
