# Generated by Django 2.2.24 on 2021-12-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20211129_1528'),
        ('Api_IntMaintenance', '0016_apibasedata_requesturlradio'),
        ('Api_CaseMaintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTestSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='排序')),
                ('pluralIntId', models.CharField(max_length=50, null=True, verbose_name='多相同接口时用-1，-2来区别,只用编辑读取中用到此id')),
                ('testName', models.CharField(max_length=50, null=True, verbose_name='测试名称')),
                ('is_synchronous', models.IntegerField(verbose_name='是否开启同步(1:开启,0:不开启)')),
                ('state', models.IntegerField(verbose_name='是否启用(1:启用,0:禁用)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('apiId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_IntMaintenance.ApiBaseData')),
                ('caseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_CaseMaintenance.CaseBaseData')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
        migrations.CreateModel(
            name='CaseApiValidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='数据排序')),
                ('checkName', models.CharField(max_length=100, verbose_name='检查值')),
                ('validateType', models.CharField(max_length=50, verbose_name='断言类型')),
                ('valueType', models.CharField(max_length=50, verbose_name='断言值类型')),
                ('expectedResults', models.TextField(verbose_name='预期结果')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
                ('state', models.IntegerField(verbose_name='是否启用(0:禁用,1:启用)')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('testSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_CaseMaintenance.CaseTestSet')),
            ],
        ),
        migrations.CreateModel(
            name='CaseApiParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='数据排序')),
                ('key', models.CharField(max_length=100, null=True, verbose_name='key')),
                ('value', models.TextField(null=True, verbose_name='value')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
                ('state', models.IntegerField(verbose_name='是否启用(0:禁用,1:启用)')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('testSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_CaseMaintenance.CaseTestSet')),
            ],
        ),
        migrations.CreateModel(
            name='CaseApiOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='数据排序')),
                ('location', models.CharField(max_length=20, verbose_name='位置 前/后(Pre,Rear)')),
                ('operationType', models.CharField(max_length=20, verbose_name='操作类型(Methods,DataBase)')),
                ('methodsName', models.CharField(max_length=100, verbose_name='函数方法')),
                ('dataBaseId', models.CharField(max_length=50, verbose_name='要执行的数据库连接ID')),
                ('sql', models.TextField(verbose_name='Sql数据')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
                ('state', models.IntegerField(verbose_name='是否启用(0:禁用,1:启用)')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('testSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_CaseMaintenance.CaseTestSet')),
            ],
        ),
        migrations.CreateModel(
            name='CaseApiHeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='数据排序')),
                ('key', models.CharField(max_length=100, null=True, verbose_name='key')),
                ('value', models.TextField(null=True, verbose_name='value')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
                ('state', models.IntegerField(verbose_name='是否启用(0:禁用,1:启用)')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('testSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_CaseMaintenance.CaseTestSet')),
            ],
        ),
        migrations.CreateModel(
            name='CaseApiExtract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='数据排序')),
                ('key', models.CharField(max_length=100, null=True, verbose_name='key')),
                ('value', models.TextField(null=True, verbose_name='value')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
                ('state', models.IntegerField(verbose_name='是否启用(0:禁用,1:启用)')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('testSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_CaseMaintenance.CaseTestSet')),
            ],
        ),
        migrations.CreateModel(
            name='CaseApiBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='数据排序')),
                ('key', models.CharField(max_length=100, null=True, verbose_name='key')),
                ('value', models.TextField(null=True, verbose_name='value/Raw参数/file')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
                ('state', models.IntegerField(verbose_name='是否启用(0:禁用,1:启用)')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('testSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_CaseMaintenance.CaseTestSet')),
            ],
        ),
        migrations.CreateModel(
            name='CaseApiBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestType', models.CharField(max_length=50, null=True, verbose_name='请求类型(GET/POST)')),
                ('requestUrl', models.CharField(max_length=500, null=True, verbose_name='请求地址')),
                ('requestParamsType', models.CharField(max_length=50, null=True, verbose_name='请求参数类型(Params、Body)')),
                ('bodyRequestSaveType', models.CharField(max_length=10, null=True, verbose_name='body数据保存类型(none,form-data,json,raw)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('testSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_CaseMaintenance.CaseTestSet')),
            ],
        ),
    ]
