# Generated by Django 2.2.24 on 2022-01-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ui_ElementEvent', '0002_remove_elementevent_onlycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementevent',
            name='eventLogo',
            field=models.CharField(default=1, max_length=20, verbose_name='事件标识'),
            preserve_default=False,
        ),
    ]
