# Generated by Django 2.2.24 on 2022-01-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ui_ElementEvent', '0004_elementeventcomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementevent',
            name='remarks',
            field=models.TextField(null=True, verbose_name='备注信息'),
        ),
    ]
