# Generated by Django 2.2.24 on 2022-01-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ui_ElementEvent', '0005_auto_20220121_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementevent',
            name='onlyCode',
            field=models.CharField(default=1, max_length=100, verbose_name='历史记录唯一码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementeventcomponent',
            name='onlyCode',
            field=models.CharField(default=1, max_length=100, verbose_name='历史记录唯一码'),
            preserve_default=False,
        ),
    ]
