# Generated by Django 2.2.24 on 2022-01-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ui_ElementEvent', '0006_auto_20220121_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementeventcomponent',
            name='value',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
    ]
