# Generated by Django 2.2.24 on 2022-01-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ui_ElementEvent', '0007_auto_20220121_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementevent',
            name='eventLogo',
            field=models.CharField(max_length=50, verbose_name='事件标识'),
        ),
    ]
