# Generated by Django 2.2.24 on 2022-01-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ui_ElementEvent', '0008_auto_20220121_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementevent',
            name='index',
            field=models.IntegerField(default=1, verbose_name='数据排序'),
            preserve_default=False,
        ),
    ]
