# Generated by Django 2.2.24 on 2022-01-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0008_auto_20211129_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysType', models.CharField(max_length=10, verbose_name='所属系统')),
                ('dbType', models.CharField(max_length=50, verbose_name='数据库类型(MySql,)')),
                ('dataBaseIp', models.CharField(max_length=50, verbose_name='IP')),
                ('port', models.CharField(max_length=10, verbose_name='端口')),
                ('userName', models.CharField(max_length=50, verbose_name='用户名')),
                ('passWord', models.CharField(max_length=50, verbose_name='密码')),
                ('remarks', models.TextField(null=True, verbose_name='备注信息')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('cuid', models.IntegerField(verbose_name='创建者用户')),
                ('is_del', models.IntegerField(verbose_name='是否删除(0:删除,1:不删除)')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
    ]
