# Generated by Django 2.2.24 on 2022-01-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBaseEnvironment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='sysType',
        ),
    ]
