# Generated by Django 2.2.24 on 2021-12-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PageEnvironment', '0001_initial'),
        ('FunManagement', '0002_funmanagement_systype'),
        ('PageManagement', '0002_pagemanagement_systype'),
        ('login', '0008_auto_20211129_1528'),
        ('ProjectManagement', '0005_probindmembers_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiName', models.CharField(max_length=100, verbose_name='接口名称')),
                ('requestType', models.CharField(max_length=50, null=True, verbose_name='请求类型(GET/POST)')),
                ('requestUrl', models.CharField(max_length=500, null=True, verbose_name='请求地址')),
                ('requestParamsType', models.CharField(max_length=10, null=True, verbose_name='请求参数类型(Params、Body)')),
                ('bodyRequestSaveType', models.CharField(max_length=10, null=True, verbose_name='body数据保存类型(none,form-data,json,raw)')),
                ('apiState', models.IntegerField(verbose_name='接口状态(InDev,Completed,Discard)')),
                ('cuid', models.IntegerField(verbose_name='创建者用户')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PageEnvironment.PageEnvironment')),
                ('fun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FunManagement.FunManagement')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PageManagement.PageManagement')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.ProManagement')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
    ]
