# Generated by Django 2.2.24 on 2021-12-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api_IntMaintenance', '0005_apibody'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiExtract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='数据排序')),
                ('key', models.CharField(max_length=100, null=True, verbose_name='key')),
                ('value', models.TextField(null=True, verbose_name='value')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
                ('state', models.IntegerField(verbose_name='是否启用(0:禁用,1:启用)')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('apiId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_IntMaintenance.ApiBaseData')),
            ],
        ),
    ]
