# Generated by Django 2.2.24 on 2021-12-06 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api_IntMaintenance', '0006_apiextract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiValidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='数据排序')),
                ('checkName', models.CharField(max_length=100, verbose_name='检查值')),
                ('validateType', models.CharField(max_length=50, verbose_name='断言类型')),
                ('valueType', models.CharField(max_length=50, verbose_name='断言值类型')),
                ('expectedResults', models.TextField(verbose_name='预期结果')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
                ('state', models.IntegerField(verbose_name='是否启用(0:禁用,1:启用)')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('apiId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_IntMaintenance.ApiBaseData')),
            ],
        ),
    ]
