# Generated by Django 2.2.24 on 2021-12-09 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_operateinfo_is_read'),
        ('login', '0008_auto_20211129_1528'),
        ('Api_IntMaintenance', '0009_auto_20211206_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAssociatedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('apiId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_IntMaintenance.ApiBaseData')),
                ('opertateInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.OperateInfo')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
    ]
