# Generated by Django 2.2.24 on 2021-12-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api_IntMaintenance', '0012_apihistory_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apihistory',
            name='onlyCode',
        ),
        migrations.AddField(
            model_name='apiassociateduser',
            name='historyId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api_IntMaintenance.ApiHistory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apibody',
            name='historyId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api_IntMaintenance.ApiHistory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiextract',
            name='historyId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api_IntMaintenance.ApiHistory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiheaders',
            name='historyId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api_IntMaintenance.ApiHistory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apioperation',
            name='historyId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api_IntMaintenance.ApiHistory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiparams',
            name='historyId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api_IntMaintenance.ApiHistory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apivalidate',
            name='historyId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api_IntMaintenance.ApiHistory'),
            preserve_default=False,
        ),
    ]
