# Generated by Django 2.2.24 on 2021-12-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_IntMaintenance', '0013_auto_20211213_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiassociateduser',
            name='historyId',
        ),
    ]
