# Generated by Django 2.2.24 on 2021-12-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api_CaseMaintenance', '0002_caseapibase_caseapibody_caseapiextract_caseapiheaders_caseapioperation_caseapiparams_caseapivalidate'),
        ('login', '0008_auto_20211129_1528'),
        ('Api_IntMaintenance', '0016_apibasedata_requesturlradio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseApiDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.IntegerField(verbose_name='是否删除(1:已看,0:未看)')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cuid', models.IntegerField(verbose_name='创建者用户')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('apiId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_IntMaintenance.ApiBaseData')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_CaseMaintenance.CaseBaseData')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserTable')),
            ],
        ),
    ]
