# Generated by Django 2.2.24 on 2021-12-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_CaseMaintenance', '0002_caseapibase_caseapibody_caseapiextract_caseapiheaders_caseapioperation_caseapiparams_caseapivalidate'),
        ('login', '0008_auto_20211129_1528'),
        ('Api_IntMaintenance', '0017_caseapidynamic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseApiDynamic',
            new_name='ApiDynamic',
        ),
    ]
