# Generated by Django 2.2.24 on 2021-12-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_IntMaintenance', '0018_auto_20211222_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='apihistory',
            name='textInfo',
            field=models.TextField(null=True, verbose_name='保存变动的文本信息'),
        ),
    ]
