# Generated by Django 2.2.24 on 2021-12-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_IntMaintenance', '0019_apihistory_textinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apibasedata',
            name='assignedToUser',
            field=models.IntegerField(default=10, verbose_name='指派给用户'),
            preserve_default=False,
        ),
    ]
