# Generated by Django 2.2.24 on 2021-12-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_IntMaintenance', '0021_auto_20211231_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='apibody',
            name='paramsType',
            field=models.CharField(default=1, max_length=10, verbose_name='入参类型(Text,File)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apibody',
            name='value',
            field=models.TextField(null=True, verbose_name='value/Raw/json/file'),
        ),
    ]
