# Generated by Django 2.2.24 on 2021-12-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_IntMaintenance', '0022_auto_20211231_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='apibody',
            name='fileList',
            field=models.TextField(null=True, verbose_name='file'),
        ),
        migrations.AddField(
            model_name='apibody',
            name='fileMD5',
            field=models.TextField(null=True, verbose_name='用于判断这个文件有没有被修改'),
        ),
        migrations.AlterField(
            model_name='apibody',
            name='value',
            field=models.TextField(null=True, verbose_name='value/Raw/json'),
        ),
    ]
