# Generated by Django 2.2.24 on 2022-01-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_IntMaintenance', '0024_auto_20211231_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apibody',
            name='fileMD5',
        ),
    ]
