# Generated by Django 2.2.24 on 2022-01-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_IntMaintenance', '0025_remove_apibody_filemd5'),
    ]

    operations = [
        migrations.AddField(
            model_name='apibasedata',
            name='historyCode',
            field=models.CharField(default=1, max_length=100, verbose_name='历史记录唯一码'),
            preserve_default=False,
        ),
    ]
