# Generated by Django 2.2.24 on 2021-12-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalVariable', '0002_globalvariable_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalvariable',
            name='globalType',
            field=models.IntegerField(verbose_name='变量类型(0:普通变量,1:全局变量)'),
        ),
    ]
