# Generated by Django 2.2.24 on 2021-12-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageEnvironment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageenvironment',
            name='remarks',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
    ]
