# Generated by Django 3.2.9 on 2021-11-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(verbose_name='内置用户ID')),
                ('userName', models.CharField(max_length=50, null=True)),
                ('nickName', models.CharField(max_length=200, null=True)),
                ('userImg', models.CharField(max_length=100, null=True)),
                ('imgMD5', models.CharField(max_length=100, null=True)),
                ('emails', models.CharField(max_length=100, null=True)),
                ('is_lock', models.IntegerField(verbose_name='是否锁定(0:不锁定,1:锁定)')),
                ('is_activation', models.IntegerField(verbose_name='是否激活(0:未激活,1:已激活)')),
                ('is_del', models.IntegerField(verbose_name='是否删除(0:不删除,1:删除)')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='登录时间')),
            ],
        ),
    ]
