# Generated by Django 3.2.9 on 2021-11-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys', models.CharField(max_length=10, verbose_name='测试类型(INT/FUN/PER)')),
                ('level', models.IntegerField(verbose_name='错误级别')),
                ('methodName', models.CharField(max_length=100, verbose_name='方法名称')),
                ('info', models.TextField(null=True, verbose_name='报错信息')),
                ('is_read', models.IntegerField(verbose_name='是否删除(0:未读,1:已读)')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
