# Generated by Django 3.2.9 on 2021-11-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20211104_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorMsg',
        ),
    ]
