# Generated by Django 3.2.9 on 2021-11-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_usertable_userimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='createTime',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
