# Generated by Django 3.2.9 on 2021-11-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_auto_20211124_1442'),
        ('login', '0006_auto_20211123_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBindRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.IntegerField(verbose_name='是否删除(1:删除,0:不删除)')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.basicrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usertable')),
            ],
        ),
    ]
